apiVersion: v1
kind: ServiceAccount
metadata:
  name: azurekeyvaultsecretsprovider-dev-aks-cluster
  namespace: dev
  annotations:
    azure.workload.identity/client-id: a89a7d91-fcba-4163-a791-63a6f0eeb300
