# Default values for aks-store-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: "dev"


# External services configuration
useRabbitMQ: false # external RabbitMQ, do not deploy in cluster
useMongoDB: false  # external MongoDB, do not deploy in cluster

# External RabbitMQ connection
rabbitmq:
  host: "dev-rabbit-host"
  port: 5672
  username: "dev-user"
  password: "dev-pass"

# External MongoDB connection
mongodb:
  host: "dev-mongo-host"
  port: 27017
  username: "dev-user"
  password: "dev-pass"
  db: "orderdb-dev"

useAzureAd: true # when true, Azure AD auth will be used for ai-service, order-service, and makeline-service
managedIdentityName: "azurekeyvaultsecretsprovider-dev-aks-cluster" # name of the Azure AD identity to use for the service account
managedIdentityClientId: "" # client ID of the managed identity to use for the service account

aiService:
  # Specifies whether a ai-service deployment and service should be created
  create: true
  modelDeploymentName: ""
  openAiEndpoint: ""
  openAiKey: ""
  openAiOrgId: ""
  useAzureOpenAi: false
  openAiDalleEndpoint: ""
  openAiDalleModelName: ""
  azureOpenAiApiVersion: "2024-12-01-preview"
  image:
    repository: "nexazdtdevacr.azurecr.io/ai-service"
    tag: "latest"


orderService:
  queueHost: "{{ .Values.rabbitmq.host }}"
  queuePort: "{{ .Values.rabbitmq.port }}"
  queueUsername: "{{ .Values.rabbitmq.username }}"
  queuePassword: "{{ .Values.rabbitmq.password }}"
  queueName: "orders"
  queueTransport: ""
  image:
    repository: "nexazdtdevacr.azurecr.io/order-service"
    tag: "{{ .Values.image.tag }}"


makelineService:
  orderQueueUri: "amqp://{{ .Values.rabbitmq.host }}:{{ .Values.rabbitmq.port }}"
  orderQueueUsername: "{{ .Values.rabbitmq.username }}"
  orderQueuePassword: "{{ .Values.rabbitmq.password }}"
  orderQueueName: "orders"
  orderQueueHost: "{{ .Values.rabbitmq.host }}"
  orderDBApi: "{{ .Values.mongodb.host }}"
  orderDBUri: "mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ .Values.mongodb.host }}:{{ .Values.mongodb.port }}/{{ .Values.mongodb.db }}"
  orderDBListConnectionStringsUrl: ""
  orderDBName: "{{ .Values.mongodb.db }}"
  orderDBCollectionName: "orders"
  orderDBContainerName: "orders"
  orderDBUsername: "{{ .Values.mongodb.username }}"
  orderDBPassword: "{{ .Values.mongodb.password }}"
  image:
    repository: "nexazdtdevacr.azurecr.io/makeline-service"
    tag: "{{ .Values.image.tag }}"

productService:
  image:
    repository: "ghcr.io/azure-samples/aks-store-demo/product-service"
    tag: "{{ .Values.image.tag }}"

storeAdmin:
  image:
    repository: "ghcr.io/azure-samples/aks-store-demo/store-admin"
    tag: "{{ .Values.image.tag }}"
  serviceType: LoadBalancer

storeFront:
  image:
    repository: "ghcr.io/azure-samples/aks-store-demo/store-front"
    tag: "{{ .Values.image.tag }}"
  serviceType: LoadBalancer

virtualCustomer:
  create: true
  image:
    repository: "ghcr.io/azure-samples/aks-store-demo/virtual-customer"
    tag: "{{ .Values.image.tag }}"
  ordersPerHour: 20

virtualWorker:
  create: true
  image:
    repository: "ghcr.io/azure-samples/aks-store-demo/virtual-worker"
    tag: "{{ .Values.image.tag }}"
  ordersPerHour: 10

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}
